### ISSUE TITLE
`AvgSampleWithMin` does not turn off sampling if throughput is below the min events per second threshold

### ISSUE THREAD

**Issue by BRMatt** [honeycombio/dynsampler-go#7]
I was looking through the code for `AvgSampleWithMin` to understand how it works and noticed that there _might_ be a case where data is always sampled until you hit the `MinEventsPerSec` threshold.

`AvgSampleWithMin{}.GetSampleRate()` has a shortcut if the sampler hasn't received any data:

https://github.com/honeycombio/dynsampler-go/blob/7f9929d9ca1f2c1a0ffa53d75e4ed40e4d48c32c/avgsamplewithmin.go#L164-L166

This flag is only set to true if `AvgSampleWithMin{}.updateMaps()` gets to the end of the function:

https://github.com/honeycombio/dynsampler-go/blob/7f9929d9ca1f2c1a0ffa53d75e4ed40e4d48c32c/avgsamplewithmin.go#L152-L155

But if the number of events seen falls below the per-second threshold, then `updateMaps()` short-circuits and configures the sampler to not sample the keys we've seen:

https://github.com/honeycombio/dynsampler-go/blob/7f9929d9ca1f2c1a0ffa53d75e4ed40e4d48c32c/avgsamplewithmin.go#L97-L107

But it never sets `haveData` to true, so `GetSampleRate()` will always return the goal sample rate.

I suppose this could happen if the sampler is running in a development environment, where it might not see enough traffic to hit the default min of 50 events/second, so never gets to the bottom of the function?

**Comment by christineyen** [comment]
cc @maplebed

**Comment by JamieDanielson** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
